// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADFcApYqo8W7K9BNhzQ-ALibRZFoWWzR8',
    appId: '1:840001834368:web:9d3faf98b21e0563fd8565',
    messagingSenderId: '840001834368',
    projectId: 'systematize-finance',
    authDomain: 'systematize-finance.firebaseapp.com',
    storageBucket: 'systematize-finance.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzENEFLyQ-10T1Yhg1npmxByC1c9pn7AQ',
    appId: '1:840001834368:android:c955dd26906f181afd8565',
    messagingSenderId: '840001834368',
    projectId: 'systematize-finance',
    storageBucket: 'systematize-finance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA1-8QkZZ9qdaV3k0kSWfUYoePvgYys30',
    appId: '1:840001834368:ios:be8555a35e8cf7bafd8565',
    messagingSenderId: '840001834368',
    projectId: 'systematize-finance',
    storageBucket: 'systematize-finance.firebasestorage.app',
    iosBundleId: 'com.example.personalFinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA1-8QkZZ9qdaV3k0kSWfUYoePvgYys30',
    appId: '1:840001834368:ios:be8555a35e8cf7bafd8565',
    messagingSenderId: '840001834368',
    projectId: 'systematize-finance',
    storageBucket: 'systematize-finance.firebasestorage.app',
    iosBundleId: 'com.example.personalFinance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADFcApYqo8W7K9BNhzQ-ALibRZFoWWzR8',
    appId: '1:840001834368:web:5c456940c8700cb2fd8565',
    messagingSenderId: '840001834368',
    projectId: 'systematize-finance',
    authDomain: 'systematize-finance.firebaseapp.com',
    storageBucket: 'systematize-finance.firebasestorage.app',
  );
}
